clc; clear; close all; 
 
%% NAMA MODEL 
modelName = 'PID_Monorail_Control'; 
new_system(modelName); 
open_system(modelName); 
 
%% STEP (SETPOINT KECEPATAN) 
add_block('simulink/Sources/Step', [modelName '/Step'], ... 
          'Time',     '0', ... 
          'Before',   '0', ... 
          'After',    '1', ... 
          'Position', [50 120 80 150]); 
 
%% SUM (ERROR) 
add_block('simulink/Math Operations/Sum', [modelName '/Sum'], ... 
          'Inputs',   '+-', ... 
          'Position', [120 120 150 150]); 
 
%% PID CONTROLLER 
add_block('simulink/Continuous/PID Controller', [modelName '/PID'], ... 
          'P',        '15', ... 
          'I',        '2', ... 
          'D',        '10', ... 
          'Position', [200 110 270 160]); 
 
%% MODEL MOTOR DC (MONORAIL) 
add_block('simulink/Continuous/Transfer Fcn', [modelName '/Motor'], ... 
          'Numerator',   '[1]', ... 
          'Denominator', '[0.5 1]', ... 
          'Position',    [350 120 420 160]); 
 
%% SCOPE 
add_block('simulink/Sinks/Scope', [modelName '/Scope'], ... 
          'Position', [500 120 550 170]); 
 
%% KONEKSI BLOK 
add_line(modelName, 'Step/1',  'Sum/1'); 
add_line(modelName, 'Motor/1', 'Sum/2'); 
add_line(modelName, 'Sum/1',   'PID/1'); 
add_line(modelName, 'PID/1',   'Motor/1'); 
add_line(modelName, 'Motor/1', 'Scope/1'); 
 
%% SIMPAN 
save_system(modelName); 
disp('Model Monorail PID berhasil dibuat!');